# name: Workflow

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: write
#   packages: write

# jobs:
#   windows:
#     name: windows-2022
#     runs-on: windows-2022
    
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Run Nuke Build
#         run: ./.nuke/build.cmd --GitHubToken ${{ secrets.GITHUB_TOKEN }} --NugetSource "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --NugetSourceName "craftify" --GitGlobalUserEmail "makslibovych@gmail.com"